from statistics import mean
from collections import defaultdict

# Judge data
judges_data = {
    "Liam": [
        {"name": "Snacker_Davis", "score": 5.75},
        {"name": "Ineedsleep", "score": 5.25},
        {"name": "CocoPommel", "score": 5.75},
        {"name": "windawine", "score": 6.25},
        {"name": "CodeSprite", "score": 6.375},
        {"name": "IncPuchay", "score": 5.25},
        {"name": "Van-Houston", "score": 2.75},
        {"name": "Vicioustrex", "score": 5.0},
        {"name": "NL", "score": 7.25},
        {"name": "Boazon", "score": 5.0},
        {"name": "Aarna", "score": 3.75},
        {"name": "TheBehemoth", "score": 3.75},
        {"name": "FallingDragon", "score": 2.75},
        {"name": "Arden Dragon", "score": 6.25},
        {"name": "RedRaven9", "score": 4.75},
        {"name": "Lore", "score": 5.625},
    ],
    "Timothy": [
        {"name": "s300080423", "score": 9.2},
        {"name": "Aarna", "score": 2.9},
        {"name": "-A--I-", "score": 7},
        {"name": "aj", "score": 3},
        {"name": "Arden Dragon", "score": 7.9},
        {"name": "awesomeorion", "score": 6.5},
        {"name": "Beans", "score": 2.3},
        {"name": "Boazon", "score": 4.8},
        {"name": "Bristlefrost", "score": 4.5},
        {"name": "CocoPommel", "score": 7.9},
        {"name": "Coder2098", "score": 3.8},
        {"name": "CodeSprite", "score": 7.5},
        {"name": "Cookie", "score": 3.1},
        {"name": "Cyan Spirit", "score": 6.5},
        {"name": "DragonStudios", "score": 3.8},
        {"name": "Dragoncode8", "score": 1.8},
        {"name": "emvalle10", "score": 2.1},
        {"name": "Eyeinthesky", "score": 3.4},
        {"name": "FallingDragon", "score": 3.2},
        {"name": "Familia de la Presa", "score": 0.9},
        {"name": "Fatima", "score": 2.8},
        {"name": "Fireball", "score": 7.8},
        {"name": "Griffinjiun", "score": 4.8},
        {"name": "Ineedsleep", "score": 3.8},
        {"name": "IncPuchay", "score": 4.8},
        {"name": "JavaCrafter", "score": 6.3},
        {"name": "JLE", "score": 8.3},
        {"name": "JSCoder", "score": 6.4},
        {"name": "KarthikeyaK", "score": 2.6},
        {"name": "Kesidedav", "score": 0.4},
        {"name": "kiaantolia", "score": 6.6},
        {"name": "lgcarnahan", "score": 0.1},
        {"name": "LichenStudios", "score": 1.6},
        {"name": "live.sadat", "score": 4.8},
        {"name": "LJE", "score": 8.3},
        {"name": "Lore", "score": 7.4},
        {"name": "MatthewSvetlev", "score": 2.3},
        {"name": "NL", "score": 9.3},
        {"name": "NonPlayerCharacter", "score": 8.8},
        {"name": "Pinkcatsoda", "score": 1.9},
        {"name": "Programmrr00", "score": 3.8},
        {"name": "RadhaJiKoDaas", "score": 3.9},
        {"name": "RealCodingPro", "score": 3.6},
        {"name": "RedRaven9", "score": 2.9},
        {"name": "SilverWolf", "score": 8.5},
        {"name": "Snacker_Davis", "score": 5.3},
        {"name": "SNAKEY_11", "score": 2},
        {"name": "SonicTheHedgehog", "score": 3.6},
        {"name": "TheBehemoth", "score": 5.5},
        {"name": "Van-Houston", "score": 4.1},
        {"name": "VetriR", "score": 6.6},
        {"name": "Vicioustrex", "score": 3.8},
        {"name": "VVhiteTiger", "score": 8.4},
        {"name": "windawine", "score": 6.1},
        {"name": "YokieBob", "score": 8.9},
    ],
    "Duke": [
        {"name": "NL", "score": 7.0},
        {"name": "Snacker_Davis", "score": 3.75},
        {"name": "Pinkcatsoda", "score": 1.875},
        {"name": "Ineedsleep", "score": 3.0},
        {"name": "Boazon", "score": 3.5},
        {"name": "windawine", "score": 5.0},
        {"name": "-A--I-", "score": 3.625},
        {"name": "TheBehemoth", "score": 4.25},
        {"name": "KarthikeyaK", "score": 3.125},
        {"name": "LichenStudios", "score": 1.5},
        {"name": "JLE", "score": 4.875},
        {"name": "FallingDragon", "score": 1.625},
        {"name": "DragonStudios", "score": 2.125},
        {"name": "Fatima", "score": 2.0},
        {"name": "VetriR", "score": 4.375},
        {"name": "Arden Dragon", "score": 5.25},
        {"name": "Coder2098", "score": 3.375},
        {"name": "JavaCrafter", "score": 4.2},
        {"name": "Cyan Spirit", "score": 6.75},
        {"name": "emvalle10", "score": 1.375},
        {"name": "Bristlefrost", "score": 3.5},
        {"name": "MatthewSvetlev", "score": 0.875},
        {"name": "Lore", "score": 4.75},
        {"name": "awesomeorion", "score": 5.175},
        {"name": "aj", "score": 1.0},
        {"name": "Familia de la Presa", "score": 0.6},
        {"name": "Van-Houston", "score": 1.4},
    ],
    "MindqueBlast": [
        {"name": "SNAKEY_11", "score": 1.75},
        {"name": "Cookie", "score": 3},
        {"name": "live.sadat", "score": 3.25},
        {"name": "Dragoncode8", "score": 2.25},
        {"name": "CocoPommel", "score": 5.875},
        {"name": "LJE", "score": 7.5},
        {"name": "Aarna", "score": 3.125},
        {"name": "Beans", "score": 2.875},
        {"name": "RadhaJiKoDaas", "score": 3.125},
        {"name": "Kesidedav", "score": 0.625},
        {"name": "SonicTheHedgehog", "score": 6},
        {"name": "kiaantolia", "score": 6.0625},
        {"name": "SilverWolf", "score": 6.3125},
        {"name": "JSCoder", "score": 4.3125},
        {"name": "NonPlayerCharacter", "score": 8},
        {"name": "CodeSprite", "score": 7.5},
        {"name": "Programmrr00", "score": 3.625},
        {"name": "IncPuchay", "score": 5.125},
        {"name": "Fireball", "score": 6.5625},
        {"name": "RedRaven9", "score": 5.25},
        {"name": "VVhiteTiger", "score": 7.625},
        {"name": "YokieBob", "score": 7.8125},
        {"name": "s300080423", "score": 9.125},
        {"name": "Vicioustrex", "score": 5.125},
        {"name": "Griffinjiun", "score": 3.875},
        {"name": "Eyeinthesky", "score": 4.375},
    ],
    "Henry": [
        {"name": "SilverWolf", "score": 5.25},
        {"name": "lgcarnahan", "score": 0.25},
        {"name": "JSCoder", "score": 4.875},
        {"name": "NonPlayerCharacter", "score": 7.125},
        {"name": "CodeSprite", "score": 6},
        {"name": "Programmrr00", "score": 3.75},
        {"name": "IncPuchay", "score": 4},
        {"name": "Fireball", "score": 5.75},
        {"name": "RedRaven9", "score": 3.125},
        {"name": "VVhiteTiger", "score": 6.625},
        {"name": "YokieBob", "score": 5},
        {"name": "s300080423", "score": 7},
        {"name": "Vicioustrex", "score": 2.625},
        {"name": "Griffinjiun", "score": 4.875},
        {"name": "Eyeinthesky", "score": 3.875},
        {"name": "RadhaJiKoDaas", "score": 3},
        {"name": "Kesidedav", "score": 1.25},
        {"name": "SonicTheHedgehog", "score": 5.5},
        {"name": "kiaantolia", "score": 4.75},
    ],
    "CodeEngineer": [
        {"name": "SNAKEY_11", "score": 4.25},
        {"name": "Cookie", "score": 7.125},
        {"name": "live.sadat", "score": 5.25},
        {"name": "Dragoncode8", "score": 3.875},
        {"name": "CocoPommel", "score": 7.625},
        {"name": "LJE", "score": 8.25},
        {"name": "Aarna", "score": 4.125},
        {"name": "Beans", "score": 3.5},
        {"name": "RadhaJiKoDaas", "score": 4.875},
        {"name": "Kesidedav", "score": 1.25},
        {"name": "SonicTheHedgehog", "score": 6.5},
        {"name": "kiaantolia", "score": 7.5},
        {"name": "SilverWolf", "score": 7.25},
        {"name": "lgcarnahan", "score": 0.5},
        {"name": "JSCoder", "score": 6.125},
        {"name": "CodeSprite", "score": 6.625},
        {"name": "Programmrr00", "score": 2},
        {"name": "IncPuchay", "score": 4.875},
        {"name": "Fireball", "score": 6.375},
        {"name": "RedRaven9", "score": 5.5},
        {"name": "NonPlayerCharacter", "score": 7.125},
        {"name": "VVhiteTiger", "score": 7.5},
        {"name": "YokieBob", "score": 7.25},
        {"name": "s300080423", "score": 8.5},
        {"name": "Vicioustrex", "score": 7},
        {"name": "Griffinjiun", "score": 3.75},
        {"name": "Eyeinthesky", "score": 5.75},
    ],
    "TML": [
        {"name": "SNAKEY_11", "score": 3.75},
        {"name": "Cookie", "score": 4.75},
        {"name": "live.sadat", "score": 2.5},
        {"name": "Dragoncode8", "score": 3.5},
        {"name": "CocoPommel", "score": 7.0},
        {"name": "LJE", "score": 6.5},
        {"name": "Aarna", "score": 4.25},
        {"name": "Beans", "score": 3.75},
        {"name": "RadhaJiKoDaas", "score": 3.625},
        {"name": "SonicTheHedgehog", "score": 6.375},
        {"name": "kiaantolia", "score": 5.25},
        {"name": "SilverWolf", "score": 5.0},
        {"name": "lgcarnahan", "score": 1.0},
        {"name": "JSCoder", "score": 2.375},
        {"name": "NonPlayerCharacter", "score": 6.25},
        {"name": "CodeSprite", "score": 4.5},
        {"name": "Programmrr00", "score": 2.5},
        {"name": "IncPuchay", "score": 2.625},
        {"name": "Fireball", "score": 6.0},
        {"name": "RedRaven9", "score": 3.75},
        {"name": "VVhiteTiger", "score": 6.75},
        {"name": "YokieBob", "score": 7.0},
        {"name": "s300080423", "score": 7.5},
        {"name": "Vicioustrex", "score": 2.25},
        {"name": "Griffinjiun", "score": 5.0},
        {"name": "Eyeinthesky", "score": 3.75},
    ],
    "CanonRouge24": [
        {"name": "Pinkcatsoda", "score": 5.375},
        {"name": "LJE", "score": 7.375},
        {"name": "RealCodingPro", "score": 8.25},
        {"name": "NL", "score": 8.5},
        {"name": "Boazon", "score": 5.375},
        {"name": "Aarna", "score": 3.75},
        {"name": "Cookie", "score": 5.25},
        {"name": "-A--I-", "score": 6.875},
        {"name": "Beans", "score": 4.375},
        {"name": "SNAKEY_11", "score": 5},
        {"name": "Snacker_Davis", "score": 6.75},
        {"name": "Ineedsleep", "score": 6.75},
        {"name": "CocoPommel", "score": 6.875},
        {"name": "live.sadat", "score": 5.875},
        {"name": "Dragoncode8", "score": 3.75},
        {"name": "windawine", "score": 5.25},
        {"name": "Eyeinthesky", "score": 3.75},
    ],
    "Radar": [
        {"name": "s300080423", "score": 9},
        {"name": "Aarna", "score": 2.5},
        {"name": "-A--I-", "score": 4.5},
        {"name": "aj", "score": 3.125},
        {"name": "Arden Dragon", "score": 5.625},
        {"name": "awesomeorion", "score": 7.375},
        {"name": "Beans", "score": 2.125},
        {"name": "Boazon", "score": 5},
        {"name": "Bristlefrost", "score": 6.25},
        {"name": "CocoPommel", "score": 6.625},
        {"name": "Coder2098", "score": 5.5},
        {"name": "CodeSprite", "score": 6.75},
        {"name": "Cookie", "score": 6.5},
        {"name": "Cyan Spirit", "score": 6.375},
        {"name": "DragonStudios", "score": 3.25},
        {"name": "Dragoncode8", "score": 4},
        {"name": "emvalle10", "score": 2},
        {"name": "Eyeinthesky", "score": 4.25},
        {"name": "FallingDragon", "score": 5.375},
        {"name": "Familia de la Presa", "score": 2.125},
        {"name": "Fatima", "score": 4},
        {"name": "Fireball", "score": 6.75},
        {"name": "Griffinjiun", "score": 3.875},
        {"name": "Ineedsleep", "score": 3.5},
        {"name": "IncPuchay", "score": 5.5},
        {"name": "JavaCrafter", "score": 5.5},
        {"name": "JLE", "score": 7.75},
        {"name": "JSCoder", "score": 6},
        {"name": "KarthikeyaK", "score": 4.125},
        {"name": "Kesidedav", "score": 0.5},
        {"name": "kiaantolia", "score": 6.5},
        {"name": "lgcarnahan", "score": 0.25},
        {"name": "LichenStudios", "score": 2.5},
        {"name": "live.sadat", "score": 5},
        {"name": "LJE", "score": 7.5},
        {"name": "Lore", "score": 6.75},
        {"name": "MatthewSvetlev", "score": 2},
        {"name": "NL", "score": 7.875},
        {"name": "NonPlayerCharacter", "score": 8.8},
        {"name": "Pinkcatsoda", "score": 3.25},
        {"name": "Programmrr00", "score": 3.25},
        {"name": "RadhaJiKoDaas", "score": 3.625},
        {"name": "RealCodingPro", "score": 0},
        {"name": "RedRaven9", "score": 4.75},
        {"name": "SilverWolf", "score": 6.25},
        {"name": "Snacker_Davis", "score": 5.5},
        {"name": "SNAKEY_11", "score": 3.875},
        {"name": "SonicTheHedgehog", "score": 6.25},
        {"name": "TheBehemoth", "score": 5.375},
        {"name": "Van-Houston", "score": 3.75},
        {"name": "VetriR", "score": 5.5},
        {"name": "Vicioustrex", "score": 5},
        {"name": "VVhiteTiger", "score": 7},
        {"name": "windawine", "score": 5},
        {"name": "YokieBob", "score": 6.5},
    ],
}

# Combine all scores
contestant_scores = defaultdict(list)
for judge_scores in judges_data.values():
    for entry in judge_scores:
        contestant_scores[entry["name"]].append(entry["score"])

# Calculate average score per contestant
averages = {name: round(mean(scores), 3) for name, scores in contestant_scores.items()}
sorted_averages = dict(sorted(averages.items(), key=lambda x: -x[1]))
for rank, (name, avg) in enumerate(sorted_averages.items(), start=1):
    print(f"{rank}. {name}: {avg:.3f}")
